# -*- coding: utf-8 -*-
"""lmp_get_density.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RWToP_xu8kPDXBCytVDap8Q4LV6sdLlk

This notebook presents the code to extract the ensemble averages from LAMMPS simualtions.
"""

# Fernando Carmona 3/15/2024

# If not installed install lammps_logfile
# ! pip install lammps_logfile

# Import things that are needed generically
from langchain.pydantic_v1 import BaseModel, Field
from langchain.tools import BaseTool, StructuredTool, tool
import os
from dotenv import load_dotenv

## Load default OpenAI chatbot
from langchain_openai import ChatOpenAI
from langchain.agents import AgentExecutor,create_react_agent,create_openai_functions_agent # To load simple ReAct agent. Reason an act
from langchain import hub
import os
import warnings
warnings. filterwarnings('ignore')

import lammps_logfile as lmplog
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# This function reads the last time series on a given file

def parse_file(filename):
    # Open the file
    with open(filename, 'r') as file:
        lines = file.readlines()

    # Find the index of the last line starting with 'Step'
    step_index = None
    for i, line in reversed(list(enumerate(lines))):
        if line.strip().startswith('Step'):
            step_index = i
            break

    if step_index is None:
        print("No line starting with 'Step' found in the file.")
        return None, None

    # Find the first line with numbers after the 'Step' line
    numbers_line_index = None
    for i in range(step_index + 1, len(lines)):
        if any(c.isdigit() or c == '.' or c == '-' for c in lines[i]):
            numbers_line_index = i
            break

    if numbers_line_index is None:
        print("No lines with numbers found after the 'Step' line.")
        return None, None

    # Get the header line
    header = lines[step_index].strip().split()

    # Get the line with numbers
    numbers_line = lines[numbers_line_index].strip().split()

    # Check if the number of columns matches the header
    if len(numbers_line) != len(header):
        print("Number of columns in the line with numbers doesn't match the header.")
        return None, None

    # Read the rest of the time series
    time_series = []
    for i in range(numbers_line_index, len(lines)):  # Adjusted loop range
        if not lines[i].strip().split()[0].isdigit():
            break
        time_series.append(lines[i].strip().split())

    # Convert time series to NumPy array
    time_series = np.array(time_series, dtype=float)

    return header, time_series

# Example usage:
header, time_series = parse_file('380_npt_thermostyle.txt')
time_series.shape

# define file name
filename = "log.lammps_test"

# Load the log file and print the keywords
header, time_series = parse_file(filename)
print(f"Keywords: {header}")

## Get the time, Temp, density
time = time_series[:, header.index("Time")] # ns
Temp = time_series[:, header.index("Temp")] # K
density = time_series[:, header.index("Density")] # g/cm^3
lx = time_series[:, header.index("Lx")] # Angstrom

## print the average values
print(f'Temp: {Temp} K')

plt.figure()
plt.plot(time_series[:, header.index("Step")], time_series[:, header.index("Density")])
plt.xlabel("Time Step")
plt.ylabel("Density [g/cm3]")
plt.title("Density Trajectory from a MD Simulation")

## Define a fucntion to compute an ensemble average

def get_property_ensemble_average(filename, property, tolerance=0.01, graphing=False, save=False, window=50):
    converged = False

    # Load the log file
    header, time_series = parse_file(filename)

    # get data from log file
    property_data = time_series[:, header.index(property)]

    # get data from log file
    timestep_data = time_series[:, header.index("Step")]

    # convert extracted property data into df
    property_df = pd.DataFrame(data=property_data)

    # calculate cumulative running average
    cum_running_average_df = property_df.expanding().mean()

    # Turn CRA into flat np.array
    cum_running_average = cum_running_average_df.to_numpy().flatten()

    # Looping parameters
    change_of_CRA = []  # log of percent changes not meeting tolerance
    time_change_of_CRA = []  # log of time indexes where tolerance is not met
    time_change_index = -1  # Counter to keep track of when cutoff is done for graphing

    for ii in np.arange(window, len(cum_running_average_df), window):

        point_1 = cum_running_average[ii - window]
        point_2 = cum_running_average[ii]
        percent_change = np.abs(point_1 - point_2) / np.abs(point_2) * 100

        if percent_change >= tolerance:
            time_change_index = time_change_index + 1
            change_of_CRA = np.append(change_of_CRA, percent_change)
            time_change_of_CRA = np.append(time_change_of_CRA, timestep_data[ii])
        else:
            index_of_tolerance_met = ii
            converged = True
            break

    # Graphing
    if graphing or save:
        rolling_running_average_df = property_df.rolling(window).mean()
        rolling_running_average = rolling_running_average_df.to_numpy().flatten()

        fig, ax1 = plt.subplots()

        ax1.set_xlabel('Step')
        ax1.set_ylabel(property)
        ax1.plot(timestep_data, property_data, label=property)
        ax1.plot(timestep_data, cum_running_average, label='Cumulative Running Average')
        ax1.plot(timestep_data, rolling_running_average, label='Rolling Running Average', color='black')

        plt.legend(loc="lower right", bbox_to_anchor=(0.4, -0.3))

        ax2 = ax1.twinx()  # instantiate cum_running_average second axes that shares the same x-axis
        ax2.set_ylabel('% Change of Cumulative Running Average')  # we already handled the x-label with ax1
        ax2.plot(time_change_of_CRA, change_of_CRA, label='% Change of Cumulative Running Average', color='tab:green')

        if converged is True:
            ax2.plot([time_change_of_CRA[time_change_index], time_change_of_CRA[time_change_index]],
                     [np.min(change_of_CRA), np.max(change_of_CRA)],
                     color='tab:red', label='Cutoff')

        fig.tight_layout()  # otherwise the right y-label is slightly
        plt.legend(loc="lower left", bbox_to_anchor=(0.4, -0.3))

        if save is not False:
            plt.savefig("./" + property + "_trajectory.png")

    # extract Production data
    if converged is True:
        equilibrium_property_data = property_data[index_of_tolerance_met:]
        equilibrium_time_data = timestep_data[index_of_tolerance_met:]
        equilibrium_production_data = np.vstack((equilibrium_time_data, equilibrium_property_data))
        print(np.mean(equilibrium_production_data[1]))
        return converged, equilibrium_production_data, np.mean(equilibrium_production_data[1])

    elif converged is False:
        return converged, property_data, np.mean(property_data[1])

## Test the functions
filename = "log.lammps_test"
keyword = "Density"
converged, keyword_data, ensemble_average = get_property_ensemble_average(filename, keyword, graphing=True)
print(f'{keyword} Converged?: {converged}, Average {keyword}: {ensemble_average}')

## Now lets convert the functions into tools

## Define class for description of inputs in structured tool
class MultiplyInputs(BaseModel):
    filename: str = Field(description="File name of lammps log file",)
    property: str = Field(description="Property of interest to check convergence for")

# Define function in the class to be used as a tool
def check_property_convergence(filename: str, property: str) -> bool:
    """
    Check if the property has converged and provide the ensemble average.

    Arguments:
        filename: string -> log file from lammps holding all properties
        property: String -> Property of interest to check convergence and compute ensemble average
        tolerance=0.01 : Float -> Convergence criteria. Tolerance for cummulative running average to meet for convergence
        window=50 : Interger -> Window to verify if cummulative running average has changed below convergence criteria

    Returns:
        converged: Bool -> wether property converged

    """
    converged = False

    tolerance=0.01

    window=50

    # Load the log file
    header, time_series = parse_file(filename)

    # get data from log file
    property_data = time_series[:, header.index(property)]

    # get data from log file
    timestep_data = time_series[:, header.index("Step")]

    # convert extracted property data into df
    property_df = pd.DataFrame(data=property_data)

    # calculate cumulative running average
    cum_running_average_df = property_df.expanding().mean()

    # Turn CRA into flat np.array
    cum_running_average = cum_running_average_df.to_numpy().flatten()

    # Looping parameters
    change_of_CRA = []  # log of percent changes not meeting tolerance
    time_change_of_CRA = []  # log of time indexes where tolerance is not met
    time_change_index = -1  # Counter to keep track of when cutoff is done for graphing

    for ii in np.arange(window, len(cum_running_average_df), window):

        point_1 = cum_running_average[ii - window]
        point_2 = cum_running_average[ii]
        percent_change = np.abs(point_1 - point_2) / np.abs(point_2) * 100

        if percent_change >= tolerance:
            time_change_index = time_change_index + 1
            change_of_CRA = np.append(change_of_CRA, percent_change)
            time_change_of_CRA = np.append(time_change_of_CRA, timestep_data[ii])
        else:
            index_of_tolerance_met = ii
            converged = True
            break

    # Graphing
    rolling_running_average_df = property_df.rolling(window).mean()
    rolling_running_average = rolling_running_average_df.to_numpy().flatten()

    fig, ax1 = plt.subplots()

    ax1.set_xlabel('Step')
    ax1.set_ylabel(property)
    ax1.plot(timestep_data, property_data, label=property)
    ax1.plot(timestep_data, cum_running_average, label='Cumulative Running Average')
    ax1.plot(timestep_data, rolling_running_average, label='Rolling Running Average', color='black')

    plt.legend(loc="lower right", bbox_to_anchor=(0.4, -0.3))

    ax2 = ax1.twinx()  # instantiate cum_running_average second axes that shares the same x-axis
    ax2.set_ylabel('% Change of Cumulative Running Average')  # we already handled the x-label with ax1
    ax2.plot(time_change_of_CRA, change_of_CRA, label='% Change of Cumulative Running Average', color='tab:green')

    if converged is True:
        ax2.plot([time_change_of_CRA[time_change_index], time_change_of_CRA[time_change_index]],
                 [np.min(change_of_CRA), np.max(change_of_CRA)],
                 color='tab:red', label='Cutoff')

    fig.tight_layout()  # otherwise the right y-label is slightly
    plt.legend(loc="lower left", bbox_to_anchor=(0.4, -0.3))

    plt.savefig("./" + property + "_trajectory.png")

    return converged

## Define Structured Tool
convergence_tool = StructuredTool.from_function(
    func=check_property_convergence, # Function to be used
    name="Check_convergence_tool", # Name of the tool
    description="See if a property has converged. If it did it would retunr the ensenble average if not it would return a False.", # Description of the tool
    args_schema=MultiplyInputs, # Schema of the inputs defined in class
    return_direct=False, # Return the output directly
    handle_error=True, # Handle errors
    # Use dictionary as input
)

print(convergence_tool.name)
print(convergence_tool.description)
print(convergence_tool.args)

## Now lets convert the functions into tools

## Define class for description of inputs in structured tool
class MultiplyInputs(BaseModel):
    filename: str = Field(description="File name of lammps log file",)
    property: str = Field(description="Property of interest to check convergence for")

# Define function in the class to be used as a tool
def get_property_ensemble_average(filename: str, property: str) -> bool:
    """
    Check if the property has converged and provide the ensemble average.

    Arguments:
        filename: string -> log file from lammps holding all properties
        property: String -> Property of interest to check convergence and compute ensemble average
        tolerance=0.01 : Float -> Convergence criteria. Tolerance for cummulative running average to meet for convergence
        window=50 : Interger -> Window to verify if cummulative running average has changed below convergence criteria

    Returns:
        converged: Bool -> wether property converged

    """
    converged = False

    tolerance=0.01

    window=50

    # Load the log file
    header, time_series = parse_file(filename)

    # get data from log file
    property_data = time_series[:, header.index(property)]

    # get data from log file
    timestep_data = time_series[:, header.index("Step")]

    # convert extracted property data into df
    property_df = pd.DataFrame(data=property_data)

    # calculate cumulative running average
    cum_running_average_df = property_df.expanding().mean()

    # Turn CRA into flat np.array
    cum_running_average = cum_running_average_df.to_numpy().flatten()

    # Looping parameters
    change_of_CRA = []  # log of percent changes not meeting tolerance
    time_change_of_CRA = []  # log of time indexes where tolerance is not met
    time_change_index = -1  # Counter to keep track of when cutoff is done for graphing

    for ii in np.arange(window, len(cum_running_average_df), window):

        point_1 = cum_running_average[ii - window]
        point_2 = cum_running_average[ii]
        percent_change = np.abs(point_1 - point_2) / np.abs(point_2) * 100

        if percent_change >= tolerance:
            time_change_index = time_change_index + 1
            change_of_CRA = np.append(change_of_CRA, percent_change)
            time_change_of_CRA = np.append(time_change_of_CRA, timestep_data[ii])
        else:
            index_of_tolerance_met = ii
            converged = True
            break

    # Graphing
    rolling_running_average_df = property_df.rolling(window).mean()
    rolling_running_average = rolling_running_average_df.to_numpy().flatten()

    fig, ax1 = plt.subplots()

    ax1.set_xlabel('Step')
    ax1.set_ylabel(property)
    ax1.plot(timestep_data, property_data, label=property)
    ax1.plot(timestep_data, cum_running_average, label='Cumulative Running Average')
    ax1.plot(timestep_data, rolling_running_average, label='Rolling Running Average', color='black')

    plt.legend(loc="lower right", bbox_to_anchor=(0.4, -0.3))

    ax2 = ax1.twinx()  # instantiate cum_running_average second axes that shares the same x-axis
    ax2.set_ylabel('% Change of Cumulative Running Average')  # we already handled the x-label with ax1
    ax2.plot(time_change_of_CRA, change_of_CRA, label='% Change of Cumulative Running Average', color='tab:green')

    if converged is True:
        ax2.plot([time_change_of_CRA[time_change_index], time_change_of_CRA[time_change_index]],
                 [np.min(change_of_CRA), np.max(change_of_CRA)],
                 color='tab:red', label='Cutoff')

    fig.tight_layout()  # otherwise the right y-label is slightly
    plt.legend(loc="lower left", bbox_to_anchor=(0.4, -0.3))

    plt.savefig("./" + property + "_trajectory.png")

        # extract Production data
    if converged is True:
        equilibrium_property_data = property_data[index_of_tolerance_met:]
        equilibrium_time_data = timestep_data[index_of_tolerance_met:]
        equilibrium_production_data = np.vstack((equilibrium_time_data, equilibrium_property_data))
        return np.mean(equilibrium_production_data[1])

    else:
        return False

## Define Structured Tool
average_tool = StructuredTool.from_function(
    func=get_property_ensemble_average, # Function to be used
    name="Get_ensemble_average_tool", # Name of the tool
    description="Computes the ensemble average of a property. Returns False if the property is not converged", # Description of the tool
    args_schema=MultiplyInputs, # Schema of the inputs defined in class
    return_direct=False, # Return the output directly
    handle_error=True, # Handle errors
    # Use dictionary as input
)

print(average_tool.name)
print(average_tool.description)
print(average_tool.args)

"""## Load agent and add lammps_log_get Agent

"""

## Load default OpenAI chatbot
from langchain_openai import ChatOpenAI
from langchain.agents import AgentExecutor,create_react_agent # To load simple ReAct agent. Reason an act
from langchain import hub
import os
import warnings
warnings. filterwarnings('ignore')

# Define API key for OPenAI
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "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")

## Define LLM
llm = ChatOpenAI(model="gpt-3.5-turbo", openai_api_key=OPENAI_API_KEY, temperature=0.0)

# Define list of tools the LLM is going to use
tools = [convergence_tool, average_tool]

# Get the template prompt to use - you can modify this!
prompt = hub.pull("hwchase17/openai-functions-agent")

## Read the prompt template
#print(prompt)

# Creat ReAct Agent
#agent = create_react_agent(llm=llm, tools=tools, prompt=prompt)

# Create OpenAI functions agent
agent = create_openai_functions_agent(llm=llm, tools=tools, prompt=prompt)

# ## Create Agent executor
agent_executor = AgentExecutor(agent=agent,tools=tools,verbose=False,handle_parsing_errors=True)

## Run the agent executor. Remember that the name of the generated file was defined as 'test' in the function for testing putposes.

input = f'Has the Density in the LAMMPS log file called 380_npt_thermostyle.txt file converged?'
output = agent_executor.invoke({"input": str(input)})
output['output']

## Run the agent executor. Remember that the name of the generated file was defined as 'test' in the function for testing putposes.

input = f'Has the Density in the LAMMPS log file called log.lammps_test file converged if so what is the average?'
output = agent_executor.invoke({"input": str(input)})
output['output']

## Run the agent executor. Remember that the name of the generated file was defined as 'test' in the function for testing putposes.

input = f'Has the Volume in the LAMMPS log file called bad_log.lammps_test file converged if so what is the average?'
output = agent_executor.invoke({"input": str(input)})
output['output']

