atom_style full
units           real
pair_style      lj/cut 12.500
bond_style      harmonic
angle_style     hybrid cosine/periodic fourier
dihedral_style  harmonic
improper_style  fourier
pair_modify     tail yes mix arithmetic
special_bonds   lj/coul 0.0 0.0 1.0
atom_style full
units real
bond_style harmonic
angle_style harmonic
dihedral_style opls
improper_style harmonic
pair_style lj/cut/coul/long 11.0 11.0
pair_modify mix arithmetic
special_bonds lj/coul 0.0 0.0 0.5
kspace_style pppm 0.0001
